# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='required_tags',
            field=models.ManyToManyField(related_name='required_tags', to='main_app.Tag'),
        ),
    ]
